version: '3.8'
services:
  app:
    build: .
    restart: always
    depends_on:
      - postgres
    ports:
      - ${PORT}:${PORT}
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: root
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
