version: '3.8'
services:
  app:
    container_name: app
    build: .
    restart: unless-stopped

    env_file:
      - .env
    ports:
    - ${PORT}:${PORT}
    volumes:
      - .:/usr/app/src
      - /usr/app/node_modules
    environment:
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
      POSTGRES_DB: POSTGRES_DB
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
    depends_on:
      - postgres
    networks:
      - frontend

  postgres:
    container_name: postgres
    build: ./prisma
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_logs:/var/log/postgresql/postgresql.log
    networks:
      - frontend
networks:
      frontend:
        driver: bridge

volumes:
  postgres_logs:
  postgres_data: