version: '3.8'
services:
  app:
    build: .
    restart: always
    depends_on:
      - postgress
    ports:
      - "4000:4000"
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: root
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
