version: '3.8'
services:
  app:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    ports:
    - ${PORT}:${PORT}
    volumes:
      - .:/usr/app/src
      - /usr/app/node_modules
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_URL=DATABASE_URL
    depends_on:
      - postgres
    networks:
      - frontend

  postgres:
    build: ./prisma
    restart: unless-stopped
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_logs:/var/log/postgresql/postgresql.log
    networks:
      - frontend
networks:
      frontend:
        driver: bridge

volumes:
  postgres_logs:
  postgres_data: