version: '3.8'
services:
  app:
    build: .
    restart: always
    depends_on:
      - postgres
    ports:
      - ${PORT}:${PORT}
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: nest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - 5432:5432
